services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pokerdb
      POSTGRES_USER: poker
      POSTGRES_PASSWORD: poker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_DSN: postgresql://poker:poker@db:5432/pokerdb
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        ./scripts/migrate.sh &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
